package demo_project.service.impl;

import week_3_curriculum.demo_project.enums.CourseOffer;
import week_3_curriculum.demo_project.enums.Gender;
import week_3_curriculum.demo_project.model.Course;
import week_3_curriculum.demo_project.model.Teacher;
import org.junit.jupiter.api.Test;
import week_3_curriculum.demo_project.service.impl.TeachableServiceImpl;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.*;

class TeachableServiceImplTest {

    @Test
    void itShouldBeAbleToTeachCourse() {
        //Arrange

        // Create a mock Teacher object
        Teacher teacherInput = new Teacher("John Doe", 35, Gender.MALE);

        // Create a mock Course object
        Course courseInput = new Course(CourseOffer.JAVA);

        // Create an instance of TeacherServiceImpl
        TeachableServiceImpl teachableService = new TeachableServiceImpl();

        // Redirect System.out to ByteArrayOutputStream for testing, this help us retreive the output from the console
        // this is done to capture the output from the console generated by the methods being tested, so it can be compared later
        ByteArrayOutputStream actualContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(actualContent));


        //Act
        // call the method being tested
        teachableService.teachCourse(teacherInput, courseInput);

        // Retrieve the output from the console
        String expected = "FullName : John Doe\nGender : MALE\nAge : 35\nCourse taught : JAVA\n";




        //Assert
        // use toString method to convert the byte array back to string
        assertEquals(expected, actualContent.toString());
    }

    @Test
    void itShouldBeAbleToTakeCourse() {

    }
}